spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234

app.admin.username=admin
app.admin.email=admin@example.com
app.admin.password=admin123